### ISSUE TITLE
brew install logswan

### ISSUE THREAD

**Issue by ankane** [fcambus/logswan#20]
Hey @fcambus, neat library! Just wanted to let you know that it's now available on Homebrew, so Mac users can install it (and all its dependencies) with:

```sh
brew install logswan
```

Homebrew precompiles libraries, so installation is pretty much instant 🎉 

Ref: https://github.com/Homebrew/homebrew-core/pull/68306

**Comment by fcambus** [comment]
Thanks for packaging Logswan in Homebrew, I have updated the README to point to the package.
