### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by JamieSlome** [fcambus/logswan#21]
Hey there!

I belong to an open source security research community, and a member (@geeknik) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by fcambus** [comment]
Hi,

I'm not keen on creating a SECURITY.md file as it can be abused in automated ways to spam projects.

There is an `AUTHORS` file with an email address in the repository if somebody wants to reach out privately.

Regarding security issues, I believe in full disclosure, so I would prefer if you could submit anything you find as a public issue.

**Comment by JamieSlome** [comment]
@fcambus - respect your thoughts here!

I have made the report fully visible, and you can find it here:

https://huntr.dev/bounties/640605a7-9970-4d35-bd7e-fecc9dea69bc/

**Comment by fcambus** [comment]
Thanks, the issue is valid and was fixed in c3fc63fe8661d17272a5840b26a7e45cf21fb82a.

**Comment by JamieSlome** [comment]
@fcambus - thanks for the heads up! 🎉  Would you like me to go ahead and mark this against the report for you?

**Comment by fcambus** [comment]
Sure, no problem!

**Comment by JamieSlome** [comment]
@fcambus - sorted!
