### ISSUE TITLE
Logo art - who's h7/ds?

### ISSUE THREAD

**Issue by tlack** [fcambus/logswan#8]
Great project, and I am quite taken with your ascii art logo. I fondly remember ascii during my bbs and early internet days. Who drew it?

**Comment by fcambus** [comment]
Glad you like the logo! It was drawn by h7 from Divine Stylers, an Amiga ascii group. You can see more stuff from him here : http://amiga.textmod.es/~h7/

**Comment by fcambus** [comment]
Also, you might be interested in the Sixteen Colors ANSI and ASCII Artwork Archive : http://sixteencolors.net
